reflector:
  resources:
    limits:
      cpu: 100m
      memory: 512Mi
    requests:
      cpu: 50m
      memory: 350Mi

  startupProbe:
    httpGet:
      path: /health/ready
      port: http
    timeoutSeconds: 10
    initialDelaySeconds: 5
    periodSeconds: 10
    # increase from 5 to 20 to allow more time
    failureThreshold: 20

